apiVersion: v1
kind: Service
metadata:
  name: country-app-service
  namespace: country-app
spec:
  type: NodePort
  selector:
    app: country-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
